/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.alee.laf.WebLookAndFeel;
import controller.*;
import javax.swing.DefaultListModel;
import javax.swing.LookAndFeel;
import model.Ordine;

/**
 *
 * @author smart
 */
public class EliminaOrdineFrame extends javax.swing.JFrame {

    Controller mc;
    
    public EliminaOrdineFrame(Controller mc) {
        this.mc = mc;
        initComponents();
        initList();
    }
    
    private void initList() {
        this.setTitle("Elimina Ordine");
        DefaultListModel dlm = new DefaultListModel();
        ((MyController) mc).getOrdini().forEach((o) -> {
            dlm.addElement(o.toString());
        });
        ordiniList.setModel(dlm);
        ordiniList.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ordiniList = new javax.swing.JList<>();
        eliminaOrdineButton = new javax.swing.JButton();
        eliminaTuttoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        ordiniList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ordiniList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(ordiniList);

        eliminaOrdineButton.setText("Elimina ordine selezionato");
        eliminaOrdineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaOrdineButtonActionPerformed(evt);
            }
        });

        eliminaTuttoButton.setText("Elimina tutto");
        eliminaTuttoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaTuttoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eliminaOrdineButton, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminaTuttoButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminaOrdineButton)
                    .addComponent(eliminaTuttoButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminaOrdineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaOrdineButtonActionPerformed
        ((MyController) mc).eliminaOrdine(ordiniList.getSelectedIndex());
        initList();
    }//GEN-LAST:event_eliminaOrdineButtonActionPerformed

    private void eliminaTuttoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaTuttoButtonActionPerformed
        ((MyController) mc).eliminaTuttiOrdini();
        initList();
    }//GEN-LAST:event_eliminaTuttoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(Controller mc) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(new WebLookAndFeel());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminaOrdineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminaOrdineFrame(mc).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eliminaOrdineButton;
    private javax.swing.JButton eliminaTuttoButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> ordiniList;
    // End of variables declaration//GEN-END:variables
}
