/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.alee.laf.WebLookAndFeel;
import controller.*;
import java.util.ArrayList;
import java.util.HashMap;
import static java.util.stream.Collectors.toList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import model.*;

/**
 *
 * @author smart
 */
public class NuovoMenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form NuovoMenuFrame
     */
    
    Controller mc;
    RistoGUI rgui;
    
    public NuovoMenuFrame(Controller mc, RistoGUI rgui) {
        this.mc = mc;
        this.rgui = rgui;
        initComponents();
        initLists();
        rgui.updateOrdineUI();
        rgui.updateOrdineUI();
    }
    
    private void initLists() {
        this.setTitle("Nuovo Menu");
        System.out.println("[== INIT LISTE ==]");
        
        HashMap<Categoria, ArrayList<Portata>> hm = ((MyController) mc).getPortate();
        DefaultListModel dlmantipasto = new DefaultListModel();
        
        for (Portata p : hm.get(Categoria.ANTIPASTO)) {
            dlmantipasto.addElement(p.getNome());
        }
        antipastoList.setModel(dlmantipasto);
        antipastoList.setSelectedIndex(0);
        
        DefaultListModel dlmprimo = new DefaultListModel();
        for (Portata p : hm.get(Categoria.PRIMO)) {
            dlmprimo.addElement(p.getNome());
        }
        primoList.setModel(dlmprimo);
        primoList.setSelectedIndex(0);
        
        DefaultListModel dlmsecondo = new DefaultListModel();
        for (Portata p : hm.get(Categoria.SECONDO)) {
            dlmsecondo.addElement(p.getNome());
        }
        secondoList.setModel(dlmsecondo);
        secondoList.setSelectedIndex(0);
        
        DefaultListModel dlmdessert = new DefaultListModel();
        for (Portata p : hm.get(Categoria.DESSERT)) {
            dlmdessert.addElement(p.getNome());
        }
        dessertList.setModel(dlmdessert);
        dessertList.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        antipastoList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        primoList = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        secondoList = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        dessertList = new javax.swing.JList<>();
        creaMenuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setViewportView(antipastoList);

        jLabel1.setText("Nuovo menu");

        jLabel2.setText("Nome");

        nomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Antipasto");

        jLabel4.setText("Primo");

        jScrollPane2.setViewportView(primoList);

        jLabel5.setText("Secondo");

        jScrollPane3.setViewportView(secondoList);

        jLabel6.setText("Dessert");

        jScrollPane4.setViewportView(dessertList);

        creaMenuButton.setText("Crea menu");
        creaMenuButton.setToolTipText("");
        creaMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creaMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(creaMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)))
                    .addComponent(creaMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextFieldActionPerformed

    private void creaMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creaMenuButtonActionPerformed
        if (!nomeTextField.getText().isEmpty()) {
            HashMap<Categoria, ArrayList<Portata>> hm = ((MyController) mc).getPortate();
            HashMap<Categoria, ArrayList<Portata>> hmmenu = new HashMap<>();
            ArrayList<Portata> antipasti = new ArrayList<>();
            ArrayList<Portata> primi = new ArrayList<>();
            ArrayList<Portata> secondi = new ArrayList<>();
            ArrayList<Portata> dessert = new ArrayList<>();
            for (int i : antipastoList.getSelectedIndices()) {
                antipasti.add(hm.get(Categoria.ANTIPASTO).get(i));
            }
            for (int i : primoList.getSelectedIndices()) {
                primi.add(hm.get(Categoria.PRIMO).get(i));
            }
            for (int i : secondoList.getSelectedIndices()) {
                secondi.add(hm.get(Categoria.SECONDO).get(i));
            }
            for (int i : dessertList.getSelectedIndices()) {
                dessert.add(hm.get(Categoria.DESSERT).get(i));
            }
            hmmenu.put(Categoria.ANTIPASTO, antipasti);
            hmmenu.put(Categoria.PRIMO, primi);
            hmmenu.put(Categoria.SECONDO, secondi);
            hmmenu.put(Categoria.DESSERT, dessert);
            Menu m = new Menu(nomeTextField.getText(), hmmenu);
            mc.aggiungiMenu(m);
            rgui.updateOrdineUI();
            setVisible(false); //you can't see me!
            dispose();
        } else {
            ((MyController) mc).getUserInteractor().showMessage("Manca il nome del menu!");
        }
    }//GEN-LAST:event_creaMenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(Controller mc, RistoGUI rgui) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(new WebLookAndFeel());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuovoMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuovoMenuFrame(mc, rgui).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> antipastoList;
    private javax.swing.JButton creaMenuButton;
    private javax.swing.JList<String> dessertList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JList<String> primoList;
    private javax.swing.JList<String> secondoList;
    // End of variables declaration//GEN-END:variables
}
